--- Logging error ---
Traceback (most recent call last):
  File "c:\python\lib\logging\__init__.py", line 1037, in emit
    stream.write(msg + self.terminator)
OSError: [WinError 6] 句柄无效。
Call stack:
  File "c:\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python\Scripts\pytest.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "c:\python\lib\site-packages\_pytest\config\__init__.py", line 125, in main
    config=config
  File "c:\python\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\python\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\python\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\python\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\python\lib\site-packages\_pytest\main.py", line 240, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "c:\python\lib\site-packages\_pytest\main.py", line 191, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "c:\python\lib\site-packages\_pytest\main.py", line 246, in _main
    config.hook.pytest_collection(session=session)
  File "c:\python\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\python\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\python\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\python\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\python\lib\site-packages\_pytest\main.py", line 257, in pytest_collection
    return session.perform_collect()
  File "c:\python\lib\site-packages\_pytest\main.py", line 452, in perform_collect
    items = self._perform_collect(args, genitems)
  File "c:\python\lib\site-packages\_pytest\main.py", line 490, in _perform_collect
    self.items.extend(self.genitems(node))
  File "c:\python\lib\site-packages\_pytest\main.py", line 681, in genitems
    rep = collect_one_node(node)
  File "c:\python\lib\site-packages\_pytest\runner.py", line 382, in collect_one_node
    rep = ihook.pytest_make_collect_report(collector=collector)
  File "c:\python\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\python\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\python\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\python\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\python\lib\site-packages\_pytest\runner.py", line 264, in pytest_make_collect_report
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
  File "c:\python\lib\site-packages\_pytest\runner.py", line 244, in from_call
    result = func()
  File "c:\python\lib\site-packages\_pytest\runner.py", line 264, in <lambda>
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
  File "c:\python\lib\site-packages\_pytest\python.py", line 446, in collect
    self._inject_setup_module_fixture()
  File "c:\python\lib\site-packages\_pytest\python.py", line 459, in _inject_setup_module_fixture
    self.obj, ("setUpModule", "setup_module")
  File "c:\python\lib\site-packages\_pytest\python.py", line 261, in obj
    self._obj = obj = self._getobj()
  File "c:\python\lib\site-packages\_pytest\python.py", line 443, in _getobj
    return self._importtestmodule()
  File "c:\python\lib\site-packages\_pytest\python.py", line 511, in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
  File "c:\python\lib\site-packages\py\_path\local.py", line 701, in pyimport
    __import__(modname)
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\python\lib\site-packages\_pytest\assertion\rewrite.py", line 152, in exec_module
    exec(co, module.__dict__)
  File "C:\liqi\autoApiTestLiqi\run_test.py", line 28, in <module>
    pytest.main(["-v", f"--alluredir={allure_path}"])
  File "c:\python\lib\site-packages\_pytest\config\__init__.py", line 125, in main
    config=config
  File "c:\python\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\python\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\python\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\python\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\python\lib\site-packages\_pytest\main.py", line 240, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "c:\python\lib\site-packages\_pytest\main.py", line 191, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "c:\python\lib\site-packages\_pytest\main.py", line 247, in _main
    config.hook.pytest_runtestloop(session=session)
  File "c:\python\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\python\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\python\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\python\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\python\lib\site-packages\_pytest\main.py", line 272, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "c:\python\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\python\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\python\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\python\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\python\lib\site-packages\_pytest\runner.py", line 85, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "c:\python\lib\site-packages\_pytest\runner.py", line 94, in runtestprotocol
    rep = call_and_report(item, "setup", log)
  File "c:\python\lib\site-packages\_pytest\runner.py", line 186, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File "c:\python\lib\site-packages\_pytest\runner.py", line 217, in call_runtest_hook
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "c:\python\lib\site-packages\_pytest\runner.py", line 244, in from_call
    result = func()
  File "c:\python\lib\site-packages\_pytest\runner.py", line 217, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "c:\python\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\python\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\python\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\python\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\python\lib\site-packages\auto_checklog.py", line 21, in pytest_runtest_setup
    test_steps.log_new_func(item.name, str(item.fspath) )
  File "c:\python\lib\site-packages\test_steps\__init__.py", line 109, in log_new_func
    __step_info.new_func(name, path)
  File "c:\python\lib\site-packages\test_steps\__init__.py", line 87, in new_func
    self.__log_case()
  File "c:\python\lib\site-packages\test_steps\__init__.py", line 90, in __log_case
    self.step_logger.info("------------------------------------------------------")
Message: '------------------------------------------------------'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "c:\python\lib\logging\__init__.py", line 1037, in emit
    stream.write(msg + self.terminator)
OSError: [WinError 6] 句柄无效。
Call stack:
  File "c:\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python\Scripts\pytest.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "c:\python\lib\site-packages\_pytest\config\__init__.py", line 125, in main
    config=config
  File "c:\python\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\python\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\python\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\python\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\python\lib\site-packages\_pytest\main.py", line 240, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "c:\python\lib\site-packages\_pytest\main.py", line 191, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "c:\python\lib\site-packages\_pytest\main.py", line 246, in _main
    config.hook.pytest_collection(session=session)
  File "c:\python\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\python\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\python\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\python\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\python\lib\site-packages\_pytest\main.py", line 257, in pytest_collection
    return session.perform_collect()
  File "c:\python\lib\site-packages\_pytest\main.py", line 452, in perform_collect
    items = self._perform_collect(args, genitems)
  File "c:\python\lib\site-packages\_pytest\main.py", line 490, in _perform_collect
    self.items.extend(self.genitems(node))
  File "c:\python\lib\site-packages\_pytest\main.py", line 681, in genitems
    rep = collect_one_node(node)
  File "c:\python\lib\site-packages\_pytest\runner.py", line 382, in collect_one_node
    rep = ihook.pytest_make_collect_report(collector=collector)
  File "c:\python\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\python\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\python\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\python\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\python\lib\site-packages\_pytest\runner.py", line 264, in pytest_make_collect_report
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
  File "c:\python\lib\site-packages\_pytest\runner.py", line 244, in from_call
    result = func()
  File "c:\python\lib\site-packages\_pytest\runner.py", line 264, in <lambda>
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
  File "c:\python\lib\site-packages\_pytest\python.py", line 446, in collect
    self._inject_setup_module_fixture()
  File "c:\python\lib\site-packages\_pytest\python.py", line 459, in _inject_setup_module_fixture
    self.obj, ("setUpModule", "setup_module")
  File "c:\python\lib\site-packages\_pytest\python.py", line 261, in obj
    self._obj = obj = self._getobj()
  File "c:\python\lib\site-packages\_pytest\python.py", line 443, in _getobj
    return self._importtestmodule()
  File "c:\python\lib\site-packages\_pytest\python.py", line 511, in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
  File "c:\python\lib\site-packages\py\_path\local.py", line 701, in pyimport
    __import__(modname)
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\python\lib\site-packages\_pytest\assertion\rewrite.py", line 152, in exec_module
    exec(co, module.__dict__)
  File "C:\liqi\autoApiTestLiqi\run_test.py", line 28, in <module>
    pytest.main(["-v", f"--alluredir={allure_path}"])
  File "c:\python\lib\site-packages\_pytest\config\__init__.py", line 125, in main
    config=config
  File "c:\python\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\python\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\python\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\python\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\python\lib\site-packages\_pytest\main.py", line 240, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "c:\python\lib\site-packages\_pytest\main.py", line 191, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "c:\python\lib\site-packages\_pytest\main.py", line 247, in _main
    config.hook.pytest_runtestloop(session=session)
  File "c:\python\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\python\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\python\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\python\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\python\lib\site-packages\_pytest\main.py", line 272, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "c:\python\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\python\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\python\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\python\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\python\lib\site-packages\_pytest\runner.py", line 85, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "c:\python\lib\site-packages\_pytest\runner.py", line 94, in runtestprotocol
    rep = call_and_report(item, "setup", log)
  File "c:\python\lib\site-packages\_pytest\runner.py", line 186, in call_and_report
    call = call_runtest_hook(item, when, **kwds)
  File "c:\python\lib\site-packages\_pytest\runner.py", line 217, in call_runtest_hook
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "c:\python\lib\site-packages\_pytest\runner.py", line 244, in from_call
    result = func()
  File "c:\python\lib\site-packages\_pytest\runner.py", line 217, in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
  File "c:\python\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\python\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\python\lib\site-packages\pluggy\manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\python\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\python\lib\site-packages\auto_checklog.py", line 21, in pytest_runtest_setup
    test_steps.log_new_func(item.name, str(item.fspath) )
  File "c:\python\lib\site-packages\test_steps\__init__.py", line 109, in log_new_func
    __step_info.new_func(name, path)
  File "c:\python\lib\site-packages\test_steps\__init__.py", line 87, in new_func
    self.__log_case()
  File "c:\python\lib\site-packages\test_steps\__init__.py", line 91, in __log_case
    self.step_logger.info("Func %s in file: %s" % (self.case_name, self.file_name))
Message: 'Func test_s3 in file: C:\\liqi\\autoApiTestLiqi\\testcases\\Test_2.py'
Arguments: ()
